# Generated by Django 4.1.1 on 2022-12-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker_client', '0004_remove_device_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_mode',
            field=models.CharField(choices=[('ip', 'ip'), ('live', 'live')], default='ip', max_length=255),
        ),
    ]
