# Generated by Django 4.1.1 on 2022-12-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker_client', '0006_remove_location_headers_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='manufacturer',
            new_name='manfacturer',
        ),
    ]
