# Generated by Django 4.1.1 on 2022-10-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Enter your company name', max_length=255, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.company')),
                ('address', models.TextField(blank=True, help_text='Enter your company address', max_length=1500, null=True, verbose_name='Company Address')),
                ('pincode', models.CharField(blank=True, help_text='Enter pincode', max_length=12, null=True, verbose_name='Pincode')),
                ('city', models.CharField(blank=True, help_text='Enter city', max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='Enter state', max_length=255, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, help_text='Enter country', max_length=255, null=True, verbose_name='Country')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter phone number', max_length=30, null=True, verbose_name='Phone Number')),
            ],
            bases=('base.company',),
        ),
    ]
