# Generated by Django 4.1.1 on 2022-10-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_company_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='company_ptr',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
