# Generated by Django 4.1.1 on 2023-03-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fieldparameters_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldparameters',
            old_name='parapeter_group',
            new_name='parameter_group',
        ),
    ]
