# Generated by Django 4.1.1 on 2023-03-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_datamodeldecorators'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodeldecorators',
            name='data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.datamodel'),
        ),
    ]
