# Generated by Django 4.1.1 on 2022-11-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_meta_content_meta_name_alter_meta_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='content',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.CreateModel(
            name='JsonSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField(blank=True, max_length=2500, null=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.api')),
            ],
        ),
    ]
