# Generated by Django 4.1.1 on 2022-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_api_content_jsonserializer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonserializer',
            name='api',
        ),
        migrations.AddField(
            model_name='jsonserializer',
            name='api',
            field=models.ManyToManyField(blank=True, to='website.api'),
        ),
    ]
